### ISSUE TITLE
Apparently the "hacktoberfest" topic is required to be applied to the repo as well

### ISSUE THREAD

**Issue by coryallegory** [IvanLudvig/IvanLudvig.github.io#15]
So much drama this year ha.

PRs are showing as ineligible on this repository without "hacktoberfest" on the repo itself, regardless of the issue tagging.
Cheers

**Comment by oneofthedevs** [comment]
Yes, took me 1 PR before I figured that out

**Comment by IvanLudvig** [comment]
Added the "hacktoberfest" topic. Are the PRs eligible now?

**Comment by coryallegory** [comment]
Yes that did it, thanks Ivan :)
