### ISSUE TITLE
Create a Logo

### ISSUE THREAD

**Issue by IvanLudvig** [IvanLudvig/IvanLudvig.github.io#2]
Create a logo for my website. It should be simple. The website is a programming blog. The main colours should probably be black and white.

**Comment by MuhammadRizwan4** [comment]
Hello bro , what is the name of your blog ??

**Comment by IvanLudvig** [comment]
The name is "Ivan Ludvig's Blog"

**Comment by MuhammadRizwan4** [comment]
What you want in logo ?? Should your logo contain your blog name or something else ?

**Comment by IvanLudvig** [comment]
Yes, the blog name should be included in the logo.

**Comment by MuhammadRizwan4** [comment]
OK , Let me  check if I can contribute . What is the purpose of your blog ?? Is it to educate programming and if you have any slogan let me know
