### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by IvanLudvig** [IvanLudvig/IvanLudvig.github.io#8]
It would be nice to implement a dark theme on my website.

**Comment by dalmia007** [comment]
I can do this. Can you please assign this to me?

**Comment by IvanLudvig** [comment]
Sure

**Comment by dalmia007** [comment]
Hey any idea how can I view the pages or run the project to see the changes I am making?

**Comment by IvanLudvig** [comment]
The website uses jekyll and you can run it locally following these instructions: https://jekyllrb.com/docs/

**Comment by dalmia007** [comment]
thank you so much

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me.

**Comment by dalmia007** [comment]
> I am interested. I can implement.
> 
> Please assign this issue to me.

I am already working on this issue and it has been assigned to me.
